# Generated by Django 5.0.6 on 2026-06-07 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, choices=[('patna', 'Patna'), ('gaya', 'Gaya'), ('muzaffarpur', 'Muzaffarpur'), ('bhagalpur', 'Bhagalpur'), ('darbhanga', 'Darbhanga'), ('purnia', 'Purnia'), ('arrah', 'Arrah'), ('begusarai', 'Begusarai'), ('katihar', 'Katihar'), ('munger', 'Munger'), ('chapra', 'Chapra'), ('hajipur', 'Hajipur'), ('samastipur', 'Samastipur'), ('sitamarhi', 'Sitamarhi'), ('siwan', 'Siwan'), ('other', 'Other')], max_length=50)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
