# Generated by Django 5.0.6 on 2026-06-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('school_teacher', 'School Teacher'), ('school_principle', 'School Principle'), ('admin', 'Admin'), ('account', 'Account'), ('marketing', 'Marketing')], default='student', max_length=20),
        ),
    ]
