# Generated by Django 5.0.6 on 2026-06-12 19:35

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_referral_codes(apps, schema_editor):
    UserProfile = apps.get_model('authentication', 'UserProfile')
    for profile in UserProfile.objects.filter(referral_code=''):
        profile.referral_code = uuid.uuid4().hex[:8].upper()
        profile.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_role_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: add column without unique, nullable so existing rows get empty string
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(max_length=20, default='', blank=True),
            preserve_default=False,
        ),
        # Step 2: populate a unique code for every existing row
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
        # Step 3: now apply the unique constraint
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        # Step 4: add referred_by FK
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='referred_users',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
